language: scala
scala:
- 2.10.4
script: sbt clean test
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - andrey.ermolov.31@gmail.com
env:
  global:
  - secure: krfmLl4VOh9kCn8/sJTMWkFEicftnzJY+ADrQWgt9oSTU0C05b+4dxN2Yrbi6N/h6S62OA7iadGDAGV39r4oF68xrMLn0jyTU863eHnPFPvzMr0tx/8JjprVTDL6sxpKjZiSAQdqLV3FRmlbwUTvHKzDJ8cbJl9uQAXC3QX41rrldaSMJmr7CkA5A/pirK/djlJbkuASUCVdu7ztkFlwqVNXtcQkfTscFogOdB2+jzGydOFi0FCdEkI70iZMz3aEO1bIyKYifsZ2juqBKjE5LQZFl1IEihh4PitfhrllIR39JfUScB549jWZ8mK2tp17vwb8TlDzlTeYduD6Gcsabbr5sxUNko1XB8xnn9khu7q03QHl3R4i2r3pCmIvCL2JjqtqbBO/yzBL+rDdvZNb+5qVG+WNbd7caN3qSQJ842NA+t5gevcjrFedv3ENBNLSQ3PefQ+M/JvW7Zo1KHIt9JRYHYCjTQdG53CCBwuhOdTM14ZiStcctrIyT8OmrLScPUtk2QJlFZaxcNDt4mLpq7g8Mu4hhTiZT8Y/ixK1JWokshlJQMK1EiQeF5pefTiyo83Hh52BFlv4hgIMHxnLVE4Hfuqo7Mp+Zb8Ndq2JV8F/KKq2HIy5MSdrrcB2wHNpMde2NMszEJXySVvqjNbE3KVQX7cDj57KKcbGLpNbTWQ=
  - secure: Cjy+L2dMBS2nSAW4kDBQ8jzi93qe9X6jHQuZcfuDQvJ7pr0+jpUajFefJteXDpfaxdT1zkt4m2c+29wZH6pNOY+gV83Qm6rYmmLdLcwdfDTjYN4ZhQJ0hm8gyzIAWGFpfoN++FU+HyWpgJCIPgCGRudg8pKLU55ct4QJO+PH6hPxcRZHDSUoGl7e/fSHMJfwreyMvingB4r9VHaLOWoubPhqzqSef4iZ7FqslsGt8ffHSk/d/5ElJqPZR5WmUN9It4b8wQjq91pXdp4rOmG+n0a9+UmIo4hwkwKQ0VXKOfuXUaY9m0UtE+n1lrkY9hJ0w+5a0P5bq03SjMnS3xPzTD0lWkGirem/cpX/56EDaiXh28pzhoPXW+UtHiPwz0cVpdr52QQhrnno+xw6fxyrQdLKuOvezxWq+oqZI5VctMW2nzL1+JR5ZorGgCduGUm5+lVuZw3B8b7EfyyZv74oE6Xdm2wjcCorZHHru5PSTU6OYoEosQ035ZY6NmlLGHzcOgSmH6YxIN0/htFomqqc9Iie2xzHDxIbwLCKh3Ay/EJmq7jYcKXNUYonWl/7ENRbHP0nW0VsHFVrq/VJcOuXKfCb8IFT1vzLvJuNUlChFN6rQkEohV+k6RghtuKZgxfoQy+yJOypCafgCcxw1PFnLMVfSBxafDfdjhHlKRaN5PU=